name: Docker login
on: push
jobs:
  build_container:
    name: Build docker container   
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}  
