name: Build nextwebapp
on: push
jobs:
    build_project:
        name: Build Project
        runs-on: ubuntu-latest
        container: node:20
            
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: Install NPM dependencies
            run: npm install
          - name: Build project assets
            run: npm run build
          - name: Upload static site content
            uses: actions/upload-artifact@v4
            with:
                name: static-site 
                path: .next/

    release_project:
        permissions:
          contents: write 
        name: Release Project
        runs-on: ubuntu-latest
        needs: build_project
        steps:
            - name: Download static site content
              uses: actions/download-artifact@v4
            - name: Check downloaded-static-site
              run: ls -R   
            
            - name: checkout code  
              uses: actions/checkout@master
            - name: Zip site content
              uses: thedoctor0/zip-release@0.7.5
              with:
                  type: 'zip'
                  filename: 'site.zip'
        
            - name: Create Release

              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: "Automated release of the static site"    





