name: Build nextwebapp
on: push
jobs:
    build_project:
        name: Build Project
        runs-on: ubuntu-latest
        container: node:20
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: Install NPM dependencies
            run: npm install
          - name: Build project assets
            run: npm run 
          - name: Upload static site content
            uses: actions/upload-artifact@v3
            with:
                name: static-site 
                path: nextwebapp/

            

