name: Docker login
on: push
jobs:
  build_container:
    name: Build docker container   
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}  
        - name: Build and push to docker hub
          uses: docker/build-push-action@v5
          with:
              context: .
              push: true
              tags: thiexco/nextwebapp:v1.0.0